// English translations of quiz question statements (keyed by question ID)
export const questionsEn: Record<string, string> = {
  q01: "The government should prioritize increasing military force to combat armed groups.",
  q02: "Negotiating with illegal armed groups is preferable to a military solution.",
  q03: "Civilians in rural areas with high crime rates should be allowed to carry firearms.",
  q04: "Forced eradication of illicit crops is the best anti-drug strategy.",
  q05: "The state should actively intervene in the economy to reduce inequality.",
  q06: "Free trade agreements have benefited multinationals more than Colombian producers.",
  q07: "Corporate taxes should be reduced to generate more employment.",
  q08: "Land reform with redistribution of land is urgent in Colombia.",
  q09: "The healthcare system should be fully public and universal.",
  q10: "Private health insurers (EPS) should continue operating as intermediaries in the healthcare system.",
  q11: "Mental health should have the same budget priority as physical health.",
  q12: "Colombia should ban fracking and open-pit mining.",
  q13: "The energy transition should be accelerated even if it involves short-term economic costs.",
  q14: "Oil exploration is necessary to finance the country's development.",
  q15: "Taxes on large fortunes are necessary to fund social programs.",
  q16: "Public spending in Colombia is excessive and should be reduced.",
  q17: "Pensions should continue to be managed by private funds.",
  q18: "Colombia should restore full diplomatic relations with Venezuela.",
  q19: "The alliance with the United States should be the foreign policy priority.",
  q20: "Colombia should strengthen integration with Latin American countries before engaging global powers.",
  q21: "Public officials convicted of corruption should receive life sentences.",
  q22: "Political campaign financing should be exclusively public.",
  q23: "The National Police should be structurally reformed and demilitarized.",
  q24: "The minimum wage in Colombia should increase significantly every year.",
  q25: "Access to generic medicines should be prioritized over pharmaceutical patents.",
};
