// English translations of quiz question statements (keyed by question ID)
export const questionsEn: Record<string, string> = {
  q01: "The government should prioritize increasing military personnel to combat armed groups.",
  q02: "Negotiation with illegal armed groups is preferable to a military solution.",
  q03: "Civilians in rural areas with high crime rates should be allowed to carry weapons.",
  q04: "Forced eradication of illicit crops should be the main tool of anti-drug policy.",
  q05: "The state should actively intervene in the economy to reduce inequality.",
  q06: "Colombia should prioritize protecting its domestic producers, even if that means limiting or renegotiating some free trade agreements.",
  q07: "Taxes on companies should be reduced to encourage investment and job creation.",
  q08: "Land reform with redistribution of land is urgent in Colombia.",
  q09: "The healthcare system should be completely public and universal.",
  q10: "Private EPS should continue operating as intermediaries in the healthcare system instead of the state directly taking over all management.",
  q11: "Mental health should have the same budget priority as physical health.",
  q12: "Colombia should ban fracking and only allow open-pit mining under very strict environmental conditions.",
  q13: "The energy transition should be accelerated even if it involves short-term economic costs.",
  q14: "Oil exploration is necessary to finance the country's development.",
  q15: "Taxes on large fortunes are necessary to finance social programs.",
  q16: "Public spending in Colombia is excessive in many areas and should be reduced to improve state efficiency.",
  q17: "The pension system should maintain a central role for private funds in the management of pensions.",
  q18: "Colombia should maintain full diplomatic relations with Venezuela in order to better manage issues such as trade, security, and migration.",
  q19: "The alliance with the United States should be one of the main priorities of Colombia's foreign policy.",
  q20: "Colombia should strengthen its political and economic integration with Latin American countries, even if that means giving less priority to agreements with global powers.",
  q21: "Public officials convicted of corruption should receive life imprisonment.",
  q22: "Political campaign financing should be exclusively public.",
  q23: "The National Police should be deeply reformed so that it acts less like a military force and more like a civil service for citizen security.",
  q24: "The minimum wage in Colombia should increase above inflation whenever the economy allows it.",
  q25: "Access to generic medicines should be prioritized over pharmaceutical patents.",
};
