/**
 * scorer.ts — Citizen–candidate affinity engine.
 *
 * TypeScript port of backend/scorer.py `compute_affinity`. Results must stay
 * identical to the Python reference: scorer.test.ts checks this against
 * fixtures generated by scripts/generate_scorer_fixtures.py.
 */

import { AXIS_WEIGHTS } from "@/lib/topics";

/** Likert answers keyed by question ID, values 1–5. */
export type Answers = Record<string, number>;

export interface ScoringQuestion {
  id: string;
  /** Canonical topic ID the question contributes to. */
  axis: string;
  weight?: number;
  direction?: "positive" | "negative" | "neutral" | string;
}

export interface ScoringCandidate {
  id: string;
  name: string;
  /** Canonical topic ID → stance score on the 1–5 scale, null when unknown. */
  stances: Record<string, number | null | undefined>;
}

/** One candidate in the ranked quiz result. */
export interface Result {
  /** Slug ID (e.g. "paloma-valencia") — use for /candidatos/[id] links. */
  id: string;
  /** Full display name (e.g. "Paloma Valencia"). */
  candidate: string;
  /** Affinity percentage 0–100, one decimal. */
  score: number;
  /** Per-topic affinity percentage, keyed by canonical topic ID. */
  breakdown: Record<string, number>;
}

const LIKERT_INVERSION_BASE = 6;
const LIKERT_RANGE = 4;
const PERCENT = 100;

/**
 * Round like Python's built-in `round(value, digits)`: exact binary ties go to
 * the even neighbour; everything else rounds to nearest.
 */
export function pyRound(value: number, digits = 0): number {
  const factor = 10 ** digits;
  const scaled = value * factor;
  const floor = Math.floor(scaled);
  const isExactTie = scaled - floor === 0.5 && scaled / factor === value;
  if (isExactTie) {
    return (floor % 2 === 0 ? floor : floor + 1) / factor;
  }
  return Number(value.toFixed(digits));
}

/** Direction-normalised weighted average of answers per axis, on the 1–5 scale. */
function weightedAxisScores(
  answers: Answers,
  questions: readonly ScoringQuestion[],
): Map<string, number> {
  const numerator = new Map<string, number>();
  const denominator = new Map<string, number>();

  for (const question of questions) {
    const raw = answers[question.id];
    if (raw === undefined || raw === null) continue;

    const weight = question.weight ?? 1;
    const answer = question.direction === "negative" ? LIKERT_INVERSION_BASE - raw : raw;

    numerator.set(question.axis, (numerator.get(question.axis) ?? 0) + answer * weight);
    denominator.set(question.axis, (denominator.get(question.axis) ?? 0) + weight);
  }

  const result = new Map<string, number>();
  for (const [axis, totalWeight] of denominator) {
    if (totalWeight > 0) result.set(axis, (numerator.get(axis) ?? 0) / totalWeight);
  }
  return result;
}

/** Drop axes the candidate has no stance on and rescale the rest to sum to 1. */
function redistributeWeights(missingAxes: ReadonlySet<string>): [string, number][] {
  const active = Object.entries(AXIS_WEIGHTS).filter(([axis]) => !missingAxes.has(axis));
  const total = active.reduce((sum, [, weight]) => sum + weight, 0);
  if (total === 0) return [];
  return active.map(([axis, weight]) => [axis, weight / total]);
}

/** Rank candidates by weighted per-axis agreement with the citizen's answers. */
export function computeAffinity(
  answers: Answers,
  candidates: readonly ScoringCandidate[],
  questions: readonly ScoringQuestion[],
): Result[] {
  const citizenAxis = weightedAxisScores(answers, questions);

  const results = candidates.map((candidate): Result => {
    const missingAxes = new Set(
      Object.keys(AXIS_WEIGHTS).filter((axis) => candidate.stances[axis] == null),
    );

    const breakdown: Record<string, number> = {};
    let weightedSum = 0;

    for (const [axis, axisWeight] of redistributeWeights(missingAxes)) {
      const citizenScore = citizenAxis.get(axis);
      const candidateScore = candidate.stances[axis];
      if (citizenScore === undefined || candidateScore == null) continue;

      const agreement = 1 - Math.abs(citizenScore - candidateScore) / LIKERT_RANGE;
      weightedSum += agreement * axisWeight;
      breakdown[axis] = pyRound(agreement * PERCENT);
    }

    return {
      id: candidate.id,
      candidate: candidate.name,
      score: pyRound(weightedSum * PERCENT, 1),
      breakdown,
    };
  });

  return results.sort((a, b) => b.score - a.score);
}
